apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    upstream spring_backend {
        server customer-management-spring:80;
    }

    server {
        listen 80;

        location /nginx_health {
            return 200 "OK";
            add_header Content-Type text/plain;
        }

        # Bloco de proxy (mantido do seu Spring config)
        location / {
            proxy_pass http://spring_backend;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }